language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar self-update
  - php composer.phar install
  - phpunit

script: phpunit --configuration phpunit.xml --coverage-text